task: identity
gpt2_size: "12_12_768"
seed: 42
epochs: 1
steps_per_epoch: 2501
max_steps: 2501
save_every_steps: 500
save_total_limit: 20
batch_size: 64
vocab_size: 100
seq_length: 64
warmup_steps: 0
lr_schedule: constant
lr: 0.0005
weight_decay: 0.1
wandb_enable: true
wandb_project: procedural_pretraining
wandb_name: identity_len64
save_dir: pretrained_models/procedural/identity/len64/
